import { test, expect } from '@playwright/test'

test('owner manages persistent portfolio, finances, files and settings', async ({ page }) => {
  const jsErrors: string[] = []
  page.on('pageerror', e => jsErrors.push(e.message))
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('browser-test@example.test')
  await page.getByLabel('Password', { exact: true }).fill('test-only-password-123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome, Browser' })).toBeVisible()
  const nav = (name: string) => page.locator('nav').getByRole('button', { name, exact: true }).click()
  const save = async () => {
    await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  await nav('Properties')
  await page.getByRole('button', { name: 'Add property', exact: true }).click()
  await page.getByLabel('Property name', { exact: true }).fill('Browser Oak')
  await page.getByLabel('Full address').fill('123 Test Avenue')
  await save()
  await page.getByRole('button', { name: 'Units & details' }).click()
  await page.getByRole('button', { name: 'Add unit / commercial space' }).click()
  await page.getByLabel('Apartment number or space label').fill('201')
  await save()
  await nav('Leases')
  await page.getByRole('button', { name: 'Add lease', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Add tenant', exact: true })).toBeVisible()
  await page.getByLabel('Full name').fill('Alex Test')
  await page.getByLabel('Phone', { exact: true }).fill('555-0100')
  await save()
  await nav('Leases')
  await page.getByRole('button', { name: 'Add lease', exact: true }).click()
  await page.getByLabel('Unit / space').selectOption({ label: 'Browser Oak · 201' })
  await page.getByLabel('Tenants', { exact: true }).selectOption({ label: 'Alex Test' })
  await page.getByLabel('Start date').fill('2020-01-01')
  await page.getByLabel('End date').fill('2099-12-31')
  await page.getByLabel('Agreed monthly rent').fill('1500.50')
  await save()
  await page.getByRole('button', { name: 'Record deposit', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Record deposit transaction' })).toBeVisible()
  await page.getByRole('button', { name: 'Close form', exact: true }).click()
  await nav('Transactions')
  await page.getByRole('button', { name: 'Add monthly entry' }).click()
  await page.getByRole('dialog').getByLabel('Property', { exact: true }).selectOption({ label: 'Browser Oak — 123 Test Avenue' })
  await page.getByRole('dialog').getByLabel('Month', { exact: true }).fill('2026-09')
  await page.getByLabel('Rent (USD)', { exact: true }).fill('1500.50')
  await page.getByLabel('Water (USD)', { exact: true }).fill('100')
  await page.getByLabel('Expected rent for this month (optional)', { exact: true }).fill('3001')
  await page.getByLabel('Payment notes (optional)').fill('Half paid.\nBalance promised on the 20th.')
  await save()
  await page.locator('.control').filter({ hasText: 'Month' }).locator('input').fill('2026-09')
  await expect(page.locator('.metrics')).toContainText('$1,400.50')
  await page.reload()
  await nav('Transactions')
  await page.locator('.control').filter({ hasText: 'Month' }).locator('input').fill('2026-09')
  await expect(page.locator('tbody')).toContainText('$1,500.50')
  await expect(page.locator('tbody')).toContainText('Partial amount')
  await page.locator('tbody summary').filter({ hasText: 'Payment notes' }).click()
  await expect(page.locator('tbody .payment-notes p')).toContainText('Balance promised on the 20th.')
  await page.getByLabel('Search this page').fill('Balance promised')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Add monthly entry' }).click()
  await page.getByRole('dialog').getByLabel('Property', { exact: true }).selectOption({ label: 'Browser Oak — 123 Test Avenue' })
  await page.getByRole('dialog').getByLabel('Month', { exact: true }).fill('2025-09')
  await page.getByLabel('Rent (USD)', { exact: true }).fill('1500.50')
  await page.getByLabel('Water (USD)', { exact: true }).fill('100')
  await save()
  await page.getByLabel('Transactions view').selectOption('year')
  await page.getByLabel('Transactions year').selectOption('2025')
  await expect(page.locator('.metrics')).toContainText('$1,400.50')
  await expect(page.locator('tbody')).toContainText('2025-09')
  await expect(page.locator('tbody')).not.toContainText('2026-09')
  await page.getByLabel('Transactions year').selectOption('2026')
  await expect(page.locator('tbody')).toContainText('2026-09')
  await page.getByLabel('Transactions view').selectOption('month')
  await nav('Dashboard')
  await page.getByLabel('View', { exact: true }).selectOption('year')
  await page.getByLabel('Year', { exact: true }).selectOption('2025')
  await expect(page.locator('.metrics')).toContainText('$1,400.50')
  await expect(page.locator('.expense-card')).toContainText('2025 full year')
  await page.getByLabel('Year', { exact: true }).selectOption('2026')
  await expect(page.locator('.metrics')).toContainText('$1,400.50')
  await page.getByLabel('View', { exact: true }).selectOption('month')
  await nav('Reports')
  await page.getByLabel('Report period', { exact: true }).selectOption('month')
  await page.getByLabel('Report month', { exact: true }).fill('2025-09')
  await expect(page.locator('.report-comparison')).toContainText('2025-09')
  await expect(page.locator('.report-comparison')).toContainText('1 matching entries')
  const reportDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  expect((await reportDownload).suggestedFilename()).toBe('havenly-report-2025-09.csv')
  await page.getByLabel('Report period', { exact: true }).selectOption('year')
  await page.getByLabel('Report year', { exact: true }).selectOption('2025')
  await expect(page.locator('.report-comparison')).toContainText('2025 full year')
  await expect(page.locator('.recharts-bar')).toBeVisible()
  await page.locator('.recharts-rectangle').first().hover()
  await expect(page.locator('.recharts-tooltip-wrapper')).toContainText('$1,400.50')
  await nav('Documents')
  await page.locator('input[type=file]').setInputFiles({ name: 'lease.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nBrowser test\n%%EOF') })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByLabel('Property', { exact: true }).selectOption({ label: 'Browser Oak — 123 Test Avenue' })
  await save()
  await page.getByLabel('Search this page').fill('123 Test')
  await expect(page.locator('.live-row')).toContainText('lease.pdf')
  await page.reload()
  await nav('Documents')
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
  await page.getByLabel('Actions for lease.pdf').click()
  const deleteAction = page.getByRole('button', { name: 'Delete', exact: true })
  await expect(deleteAction).toBeVisible()
  await expect.poll(() => deleteAction.evaluate(element => {
    const rect = element.getBoundingClientRect()
    return rect.top >= 0 && rect.bottom <= innerHeight
  })).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByLabel('Actions for lease.pdf').click()
  await page.getByRole('button', { name: 'View document', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'lease.pdf' })).toBeVisible()
  await expect(page.locator('iframe[title="Preview of lease.pdf"]')).toHaveAttribute('src', /^blob:/)
  await page.getByRole('button', { name: 'Close preview', exact: true }).click()
  await page.getByRole('button', { name: 'Open lease.pdf', exact: true }).click()
  await expect(page.locator('iframe[title="Preview of lease.pdf"]')).toHaveAttribute('src', /^blob:/)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByLabel('Actions for lease.pdf').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('lease.pdf')
  await nav('Settings')
  await page.getByRole('button', { name: 'Edit settings' }).click()
  await page.getByLabel('Owner name').fill('Updated Owner')
  await save()
  await page.reload()
  await expect(page.locator('.workspace')).toContainText('Updated Owner')
  for (const width of [1280, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    for (const section of ['Dashboard', 'Properties', 'Tenants', 'Leases', 'Transactions', 'Documents', 'Reports', 'Settings']) {
      if (width <= 700) await page.getByLabel('Toggle navigation').click()
      await nav(section)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `${section} fits at ${width}px`).toBe(true)
    }
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel('Toggle navigation').click()
  await nav('Tenants')
  await expect(page.locator('.tenant-live')).toContainText('Alex Test')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByLabel('Toggle navigation').click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect(jsErrors).toEqual([])
})

test('every recorded month remains labeled on narrow charts', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('browser-test@example.test')
  await page.getByLabel('Password', { exact: true }).fill('test-only-password-123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: /^Welcome,/ })).toBeVisible()
  const session = await page.request.get('/api/auth/session')
  expect(session.ok(), await session.text()).toBe(true)
  const { csrf } = await session.json() as { csrf: string }
  const headers = { 'X-CSRF-Token': csrf }
  const propertyResponse = await page.request.post('/api/properties', {
    headers, data: { name: 'Axis Test Property With An Intentionally Very Long Portfolio Display Name', address: '456 Example Avenue, Suite 1200, Example City, New York 10001', kind: 'Apartment' },
  })
  expect(propertyResponse.ok(), await propertyResponse.text()).toBe(true)
  const { id } = await propertyResponse.json() as { id: number }
  const months = Array.from({ length: 12 }, (_, index) => `2026-${String(index + 1).padStart(2, '0')}`)
  for (const month of months) {
    const response = await page.request.post('/api/records', {
      headers, data: { property_id: id, month, amounts: [100000, 10000, 0, 0, 0, 0] },
    })
    expect(response.ok(), await response.text()).toBe(true)
  }
  await page.reload()
  const propertyTopBefore = await page.getByLabel('Property', { exact: true }).evaluate(element => element.getBoundingClientRect().top)
  await page.getByLabel('Property', { exact: true }).selectOption(String(id))
  const propertyFilter = page.getByLabel('Property', { exact: true })
  expect(await propertyFilter.evaluate(element => element.getBoundingClientRect().top)).toBe(propertyTopBefore)
  const propertyBox = await propertyFilter.boundingBox()
  expect(propertyBox?.width).toBeLessThanOrEqual(320)
  await expect(propertyFilter).toHaveAttribute('title', /Axis Test Property With An Intentionally Very Long Portfolio Display Name/)
  await page.locator('.control').filter({ hasText: 'Month' }).locator('input').fill('2026-08')
  const labels = page.locator('.chart-month-labels span')
  await expect(labels).toHaveCount(12)
  expect(await labels.evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))).toEqual(months)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await propertyFilter.evaluate(element => {
    const rect = element.getBoundingClientRect()
    return rect.width <= 320 && rect.right <= innerWidth && getComputedStyle(element).textOverflow === 'ellipsis'
  })).toBe(true)
  const monthlyViewWidth = await page.getByLabel('View', { exact: true }).evaluate(element => element.getBoundingClientRect().width)
  await page.getByLabel('View', { exact: true }).selectOption('year')
  expect(await page.getByLabel('View', { exact: true }).evaluate(element => element.getBoundingClientRect().width)).toBe(monthlyViewWidth)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByLabel('View', { exact: true }).selectOption('month')
  await expect(labels).toHaveCount(12)
  await page.screenshot({ path: 'test-results/chart-mobile-audit.png', fullPage: true })
  await expect(page.locator('.chart-month-labels span[aria-label="2026-08"]')).toBeVisible()
  await page.getByLabel('Toggle navigation').click()
  await page.locator('nav').getByRole('button', { name: 'Reports', exact: true }).click()
  await page.getByLabel('Property', { exact: true }).selectOption(String(id))
  await expect(page.getByLabel('Property', { exact: true })).toHaveAttribute('title', /Axis Test Property With An Intentionally Very Long Portfolio Display Name/)
  await page.getByLabel('Report period', { exact: true }).selectOption('year')
  await page.getByLabel('Report year', { exact: true }).selectOption('2026')
  await expect(page.locator('.chart-month-labels span')).toHaveCount(12)
  expect(await page.locator('.chart-month-labels span').evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))).toEqual(months)
  await page.screenshot({ path: 'test-results/report-mobile-audit.png', fullPage: true })
})

test('cleared notifications remain cleared after reload and signing back in', async ({ page, browser }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('browser-test@example.test')
  await page.getByLabel('Password', { exact: true }).fill('test-only-password-123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: /^Welcome,/ })).toBeVisible()

  const session = await page.request.get('/api/auth/session')
  const { csrf } = await session.json() as { csrf: string }
  const propertyResponse = await page.request.post('/api/properties', {
    headers: { 'X-CSRF-Token': csrf }, data: { name: 'Notice Test Property', address: '15 Example Road', kind: 'Apartment' },
  })
  expect(propertyResponse.ok()).toBe(true)
  const property = await propertyResponse.json() as { id: number }
  const unitResponse = await page.request.post('/api/units', {
    headers: { 'X-CSRF-Token': csrf }, data: { property_id: property.id, label: 'A1' },
  })
  expect(unitResponse.ok()).toBe(true)
  await page.reload()
  await expect(page.getByRole('button', { name: /Notifications, [1-9]\d* unread/ })).toBeVisible()

  const bell = page.getByRole('button', { name: /^Notifications,/ })
  await bell.click()
  const panel = page.getByRole('region', { name: 'Notifications' })
  const clear = panel.getByRole('button', { name: 'Clear all' })
  await clear.click()
  await expect(panel).toContainText('All caught up')
  await page.reload()
  await expect(page.getByRole('heading', { name: /^Welcome,/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Notifications, 0 unread' })).toBeVisible()
  await page.getByRole('button', { name: 'Notifications, 0 unread' }).click()
  await expect(page.getByRole('region', { name: 'Notifications' })).toContainText('All caught up')
  await page.getByRole('region', { name: 'Notifications' }).getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await page.getByLabel('Email', { exact: true }).fill('browser-test@example.test')
  await page.getByLabel('Password', { exact: true }).fill('test-only-password-123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Notifications, 0 unread' })).toBeVisible()

  const secondContext = await browser.newContext()
  try {
    const secondPage = await secondContext.newPage()
    await secondPage.goto('/')
    await secondPage.getByLabel('Email', { exact: true }).fill('browser-test@example.test')
    await secondPage.getByLabel('Password', { exact: true }).fill('test-only-password-123')
    await secondPage.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(secondPage.getByRole('button', { name: 'Notifications, 0 unread' })).toBeVisible()
  } finally { await secondContext.close() }
})
