import { test, expect } from '@playwright/test'

test('owner manages persistent portfolio, finances, files and settings', async ({ page }) => {
  const jsErrors: string[] = []
  page.on('pageerror', e => jsErrors.push(e.message))
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('browser-test@example.test')
  await page.getByLabel('Password', { exact: true }).fill('test-only-password-123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome, Browser' })).toBeVisible()
  const nav = (name: string) => page.locator('nav').getByRole('button', { name, exact: true }).click()
  const save = async () => {
    await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  await nav('Properties')
  await page.getByRole('button', { name: 'Add property', exact: true }).click()
  await page.getByLabel('Property name', { exact: true }).fill('Browser Oak')
  await page.getByLabel('Full address').fill('123 Test Avenue')
  await save()
  await page.getByRole('button', { name: 'Units & details' }).click()
  await page.getByRole('button', { name: 'Add unit / commercial space' }).click()
  await page.getByLabel('Apartment number or space label').fill('201')
  await save()
  await nav('Tenants')
  await page.getByRole('button', { name: 'Add tenant' }).click()
  await page.getByLabel('Full name').fill('Alex Test')
  await page.getByLabel('Phone', { exact: true }).fill('555-0100')
  await save()
  await nav('Leases')
  await page.getByRole('button', { name: 'Add lease', exact: true }).click()
  await page.getByLabel('Unit / space').selectOption({ label: 'Browser Oak · 201' })
  await page.getByLabel('Tenants', { exact: true }).selectOption({ label: 'Alex Test' })
  await page.getByLabel('Start date').fill('2020-01-01')
  await page.getByLabel('End date').fill('2099-12-31')
  await page.getByLabel('Agreed monthly rent').fill('1500.50')
  await save()
  await nav('Transactions')
  await page.getByRole('button', { name: 'Add monthly entry' }).click()
  await page.getByRole('dialog').getByLabel('Property', { exact: true }).selectOption({ label: 'Browser Oak — 123 Test Avenue' })
  await page.getByRole('dialog').getByLabel('Month', { exact: true }).fill('2026-09')
  await page.getByLabel('Rent (USD)', { exact: true }).fill('1500.50')
  await page.getByLabel('Water (USD)', { exact: true }).fill('100')
  await save()
  await page.locator('.control').filter({ hasText: 'Month' }).locator('input').fill('2026-09')
  await expect(page.locator('.metrics')).toContainText('$1,400.50')
  await page.reload()
  await nav('Transactions')
  await page.locator('.control').filter({ hasText: 'Month' }).locator('input').fill('2026-09')
  await expect(page.locator('tbody')).toContainText('$1,500.50')
  await nav('Reports')
  await expect(page.locator('.recharts-bar')).toBeVisible()
  await page.locator('.recharts-rectangle').first().hover()
  await expect(page.locator('.recharts-tooltip-wrapper')).toContainText('$1,400.50')
  await nav('Documents')
  await page.locator('input[type=file]').setInputFiles({ name: 'lease.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nBrowser test\n%%EOF') })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByLabel('Property', { exact: true }).selectOption({ label: 'Browser Oak — 123 Test Avenue' })
  await save()
  await page.getByLabel('Search this page').fill('123 Test')
  await expect(page.locator('.live-row')).toContainText('lease.pdf')
  await page.reload()
  await nav('Documents')
  await page.getByLabel('Actions for lease.pdf').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('lease.pdf')
  await nav('Settings')
  await page.getByRole('button', { name: 'Edit settings' }).click()
  await page.getByLabel('Owner name').fill('Updated Owner')
  await save()
  await page.reload()
  await expect(page.locator('.workspace')).toContainText('Updated Owner')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel('Toggle navigation').click()
  await nav('Tenants')
  await expect(page.locator('.tenant-live')).toContainText('Alex Test')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByLabel('Toggle navigation').click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect(jsErrors).toEqual([])
})
